StrandMessage refactoring
measurement-factory/squid pull request #109
Opened 2021-01-11 14:10 UTC by eduard-bagdasaryan

* Renamed HereIamMessage to StrandMessage    
* eliminated code duplication with a new
  StrandMessage::NotifyCoordinator()    
* Split TypedMsgHdr::type() into unchecked rawType() and checked type()
* Renamed and documented a couple of Ipc::MessageType members

2021-01-11 17:30 UTC, rousskov requested changes
Just a few minor remarks for now. Please do not forget to adjust the PR description after you apply the other changes we have discussed.

2021-01-11 17:30 UTC, rousskov commented on src/ipc/StrandCoord.h
> +    static void NotifyCoordinator(const MessageType, const char *tag);
We use `const` in implementation. Some compilers warn about "unnecessary" `const` in declarations.

```suggestion
    static void NotifyCoordinator(MessageType, const char *tag);
```

2021-01-11 17:30 UTC, rousskov commented on src/ipc/Coordinator.cc
> +        debugs(54, DBG_IMPORTANT, HERE << "Unhandled message type: " << message.rawType());
```suggestion
        debugs(54, DBG_IMPORTANT, "WARNING: Ignoring IPC message with an unknown type: " << message.rawType());
```

2021-01-11 22:55 UTC, eduard-bagdasaryan reviewed
Done (7dcee5d).

2021-01-11 22:55 UTC, eduard-bagdasaryan commented on src/ipc/TypedMsgHdr.h
> +    int rawType() const; ///< returns stored type or zero if none
> we should remove that msg_iovlen == 1 Must 

I think we should. We now return 0 if !msg_iov.

2021-02-01 22:33 UTC, rousskov commented
This became official PR 76: Deduplicating IPC strand messages.

2021-02-01 22:33 UTC, closed without merging